routes/web.php
<?php

/*
clear cache
*/

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    echo 'view, cache, route cache cleared successfully!';
});


Route::get('/', function () {
    if(!Auth::User()){
        if(file_exists(storage_path('installed')))
        {
            return view('auth.login');
            die();
        }else{
            header("location: public/install");
            die();
        }

    }else{
        return redirect('home');
    }
});

Route::any('callback', 'CallBackController@callBack');
Route::any('add-user', 'Admin\UserController@store');

Route::post('send-password', 'Admin\UserController@userSendPassword')->name('send-password');

Route::get('find-synonyms/{word?}', 'Admin\WordApiController@index');
Route::get('mailchimp', 'Admin\MailChimpController@index');
Route::get('cron',      'CronController@index');
Route::get('fetch-emails-cron',      'CronController@fetchEmailsCron')->name('fetch-emails-cron');
Route::get('cronejob-autoresponder-contacts', 'CronController@fetchAutorespondersContacts')->name('cronejob-autoresponder-contacts');

Route::get('schedule-autoresponders', 'CronController@scheduleAutoresponders');
Route::get('schedule-aweber-broadcast', 'CronController@scheduleAweberBroadcast');
Route::get('test-cron', 'CronController@testCron');
Route::get('aweber-fetch-contacts', 'CronController@aweberFetchContacts');
Route::get('getresponse-fetch-contacts', 'CronController@getresponseFetchContacts');
Route::get('mailchimp-fetch-contacts', 'CronController@mailchimpFetchContacts');
Route::get('activecampaign-fetch-contacts', 'CronController@activecampaignFetchContacts');
// auth autoresponders
Route::get('autoresponders-lists', 'CronController@autoresponderFetchLists');

// test

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('home', 'HomeController@index')->name('home');

    Route::get('help', 'Admin\HelpController@index')->name('help');
    Route::get('link_tracker', 'HomeController@linkTracker');
    Route::get('link_tracker_settings', 'HomeController@linkTrackerSettings');
    Route::post('link_tracker_settings_store', 'HomeController@linkTrackerSettingsStore');
});
// home chart
Route::post('load-broadcast-chart',  'HomeController@broadcastChart')->name('load-broadcast-chart');

// common routes for admin and user
Route::group(['namespace'=>'Admin','middleware' => ['auth']], function(){

    Route::resource('category',  'CategoryController');
    Route::resource('new-template',  'NewEmailTemplateController');
    Route::resource('new-template2',  'NewEmailTemplateController2');
    Route::resource('settings',  'SettingController');
    Route::resource('gen_settings',  'SettingNewController');
    Route::resource('gallery',  'GalleryController');

    Route::resource('email-header-footer-settings',  'EmailHeaderFooterController');
    Route::resource('contact_info',  'ContactInfoController');
    Route::resource('report',  'ReportController');
    Route::resource('ar-campaigns',  'ArCampaignController');
    Route::resource('email-sub-category',  'SubEmailCategoryController');
    Route::resource('contacts',  'ContactsController');
    Route::resource('app-settings',  'AppSettingsController');

    Route::resource('contact-list',  'ContactListController');
    Route::get('load_list', 'ContactListController@loadList')->name('load_list');

    /* update */
    Route::get('/update-version', function (){
        return view('admin.update.index');
    });
    Route::post('updates', 'AppSettingsController@serverUpdate');


    Route::get('profile',  'UserController@loadProfileSetting')->name('profile');
    Route::post('profile-settings',  'UserController@profileSetting')->name('profile-settings');

    Route::post('browse-gallery',  'GalleryController@browseGallery')->name('browse-gallery');

    Route::get('choose-subject',       'NewEmailTemplateController@searchSubject')->name('choose-subject');
    Route::post('email_content_by_id',  'NewEmailTemplateController@loadEmailContentByID')->name('email_content_by_id');
    Route::post('download-email',       'NewEmailTemplateController@downloadEmail')->name('download-email');
    Route::post('load-searched-email',  'NewEmailTemplateController@loadSearchedEmail')->name('load-searched-email');
    Route::post('view-email-content',  'NewEmailTemplateController@viewEmailContent')->name('view-email-content'); /// added  5-5

    Route::post('fetch-emails',  'SettingNewController@fetchEmails')->name('fetch-emails'); //setting controller
    Route::post('sharing-code-gen',  'SettingNewController@sharingCodeGenerator')->name('sharing-code-gen'); //setting controller

    Route::get('cpanel-account',  'SettingNewController@cpanelAccount')->name('cpanel-account'); //setting controller # server creation

    // my emails
    Route::get('shared-emails',  'ArCampaignController@sharedEmails')->name('shared-emails');
    Route::post('fetch-shared-emails',  'ArCampaignController@fetchSharedEmails')->name('fetch-shared-emails');

    // your email contents
    Route::get('load-your-email-contents',  'AjaxController@loadYourEmailContent')->name('load-your-email-content');

    Route::get('load-my-emails',  'AjaxController@loadMyEmails')->name('load-my-emails');
    Route::get('load-shared-emails',  'AjaxController@loadSharedEmails')->name('load-shared-emails');
    Route::get('shared-emails-detail',  'AjaxController@sharedEmailsDetail')->name('shared-emails-detail');
    Route::get('load-contacts',  'AjaxController@loadContacts')->name('load-contacts');
    Route::get('load-lists',  'AjaxController@loadLists')->name('load-lists');
    Route::get('load-open-by_emails',  'AjaxController@loadOpenByEmail')->name('load-open-by_emails');
    Route::get('load-unopen-by_emails',  'AjaxController@loadUnopenByEmail')->name('load-unopen-by_emails');

    Route::get('opened-report',  'ContactsController@showOpenReport');
    Route::get('unopened-report',  'ContactsController@showUnOpenReport');

    // load_ar_campains list of get-response/aweber
    Route::get('load_ar_api_key',  'NewEmailTemplateController@selectArApi')->name('load_ar_api_key');
    Route::get('load_ar_campaings',  'NewEmailTemplateController@loadArCampaings')->name('load_ar_campaings');


    Route::post('get-aweber-token',  'AweberController@getAccessToken')->name('get-aweber-token');
    Route::any('aweber-callback',  'AweberController@aweberCallback')->name('aweber-callback');

    Route::post('get-aweber-auth',  'AweberNewController@getAccessToken')->name('get-aweber-auth');
    Route::any('aweber-callback-auth',  'AweberNewController@aweberCallback')->name('aweber-callback-auth');

    Route::post('delete',  'AjaxController@delete')->name('delete');
    Route::post('delete-email',  'AjaxController@deleteEmail')->name('delete-email');

    // test
    Route::get('report',  'ReportController@index')->name('report');

    Route::get('autoresponder-report',  'ReportController@reportById')->name('autoresponder-report');
    Route::get('type-wise-stats',  'ReportController@typewiseReport')->name('type-wise-stats');

    Route::get('testreport',  'ReportController@test')->name('testreport');

    Route::post('private-email', 'AjaxController@privateEmail')->name('private-email');
    Route::get('load-sub-categories',  'AjaxController@loadSubCategories')->name('load-sub-categories');
    Route::get('load-sub-categories-emails',  'AjaxController@loadSubCategoriesEmails')->name('load-sub-categories-emails');
    Route::get('show_boradcast_error',  'AjaxController@showBoradcastError')->name('show_boradcast_error');
    Route::post('sync_stats',  'AjaxController@syncStats')->name('sync_stats');

    Route::post('email-sub-category/loadEdit',  'SubEmailCategoryController@loadEdit');
    Route::get('assign-category',  'SubEmailCategoryController@assignCategory')->name('assign-category');
    Route::post('save-assign-category',  'SubEmailCategoryController@saveAssignCategory')->name('save-assign-category');

    Route::post('email_sender_settings',  'SettingController@emailSenderSettings')->name('email_sender_settings');

});

Route::group(['namespace'=>'Admin','middleware' => ['auth','checkAdmin']], function(){

    Route::resource('library', 'SubjectTemplateController');
    Route::resource('email-template',  'EmailTemplateController');
//    Route::resource('category',  'CategoryController');
    Route::resource('users',  'UserController');
    Route::resource('email-settings',  'UserEmailSettings');


    Route::post('user/loadEdit',  'UserController@loadEdit');
    Route::post('category/loadEdit',  'CategoryController@loadEdit');

    Route::get('load-categories',  'AjaxController@loadCategories')->name('load-categories');

    Route::get('load-users',  'AjaxController@loadUsers')->name('load-users');

    Route::get('load-subjects',  'AjaxController@loadSubjects')->name('load-subjects');
    Route::get('load-email-content',  'AjaxController@loadEmailContent')->name('load-email-content');

    Route::post('changeStatus',  'AjaxController@changeStatus')->name('changeStatus');
    Route::get('load-emailtracking-stats',  'AjaxController@loadTrackingStats')->name('load-emailtracking-stats');

    Route::post('user-stats',  'UserController@userStats')->name('user-stats');

    Route::post('email-settings-store', 'UserEmailSettings@saveEmailSettings')->name('email-settings-store');
    Route::post('test-email', 'UserEmailSettings@testEmail')->name('test-email');

});

app/Http/Controllers/Admin/ArCampaignController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
use DB;
use App\Settings;

class ArCampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("admin.ar_campaign.my_emails");
    }

    function sharedEmails( Request $request)
    {
        return view("admin.ar_campaign.shared_emails");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // profile
    public function create()
    {
        return view('admin.ar_campaign.import_emails');
    }

    function fetchSharedEmails(Request $request)
    {

        // stop if already used
        $code = $request->shared_code;
        $explode_code = explode('-', base64_decode( $code ) );

        if (!isset($explode_code[0]) || !isset($explode_code[1]) || !isset($explode_code[2]) )
        {
            echo 4; // wrong code inserted
            exit;
        }

        if (!isset($explode_code[3]))
        {
            $type = $explode_code[0];
            $account_id = $explode_code[1];
            $user_id = $explode_code[2];
            $column = 'account_id';
        }else{
            $type = $explode_code[1];
            $account_id = $explode_code[2];
            $user_id = $explode_code[3];
            $column = 'id';
        }


        $validate = DB::table('sharing_code')
            ->where(['code' => $code, 'user_id' => $user_id ])
            ->where('user_id', '!=', Auth::user()->id )
            ->value('id');

        if ($validate)
        {

            $sub_cat_id = DB::table('email_sub_category')->where(['type' => strtolower( $type), 'user_id' => $user_id, $column => $account_id ])->value('id');
            $users_code = Auth::user()->email_shared_id;

           if ($users_code == "")
           {
                $update = DB::table('users')->where(['id' => Auth::user()->id ])->update(['email_shared_id' => $sub_cat_id]);
                if ($update)
                {
                    echo 1; // success
                }
            }else{

                $user_assigned = explode(',' , $users_code);

                if (in_array($sub_cat_id, $user_assigned))
                {
                    echo 3; // code already in use
                }else{
                    $update = DB::table('users')->where(['id' => Auth::user()->id ])->update(['email_shared_id' => $users_code.','.$sub_cat_id]);
                    if ($update)
                    {
                        echo 1; // success
                    }
                }
            }
        }else{
            echo 4; // invalid code
        }
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sub_id = $id;

        return view("admin.ar_campaign.shared_emails_detail", compact('sub_id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/ar_campaign/my_emails.blade.php
@extends('layouts.app')
@section('content')
    <style>
    .auto-stats span{
        font-size: 23px;
    }
    </style>
    <div class="content">
        <!-- Start content -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title-box pull-right">
                        <ol class="breadcrumb p-0 m-0">
                            <li> <a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="active"> My Emails </li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- imported emails templates  -->
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h3 class="card-title"> My Emails </h3>
                        </div>
                        <div class="card-content">
                            <div class="material-datatables">
                                <table id="load_datatable" class="table table-bordered table-no-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Subject</th>
                                        <th>Category</th>
                                        <th width="70">Type</th>
                                        <!--<th>Send</th>-->

                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td colspan="5">No Record found yet.</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form action="{{ route('new-template.create') }}" method="get" style="display: none;" id="use_me">
            <input type="hidden" name="use_me" value="">
        </form>

        <script>
            function submitUseMe(x){
                $('input[name="use_me"]').val($(x).data('id'));
                $('#use_me').submit();
            }
        </script>

        <script>

            $(document).ready(function(){

                $('#load_datatable').DataTable({

                    "pageLength":25,
                    "order": [[0, 'desc']],
                    processing: true,
                    serverSide: true,
                    responsive:true,
                    "drawCallback": function () {
                        //table_draw();
                        /*$("[name='status']").bootstrapSwitch();
                         changeStatus();*/
                    },
                    ajax: "{!! Route('load-my-emails') !!}",
                    columns: [
                        {data: 'id', name: 'id'},
                        {data: 'subject', name: 'email_subjects_test.subject'},
                        {data: 'category', name: 'email_sub_category.category'},
                        {data: 'type', name: 'email_sub_category.type'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                        //{data: 'sent', name: 'sent', orderable: false, searchable: false},
                    ]
                });

            });

            // make frivate

            function makePrivate(e){

                $('#loading').show();
                var id = $(e).data('id');
                var action = 'imported';

                $.post( '<?= route('private-email') ?>',
                    {id:id, action:action},
                    function(data){
                        var obj = $.parseJSON(data);
                        if(obj.res == 0){
                            refreshTable();
                            swal('Success', 'Email marked as public successfully!' , 'success');
                        }
                        if(obj.res == 1){
                            refreshTable();
                            swal('Success', 'Email marked as private successfully!' , 'success');
                        }
                        $('#loading').hide();
                    });
            }

        </script>


    </div>
    <!-- Counter js  -->
    <script src="{{ asset('plugins/waypoints/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('plugins/counterup/jquery.counterup.min.js') }}"></script>
@endsection

resources/views/admin/ar_campaign/shared_emails.blade.php
@extends('layouts.app')
@section('content')
    <style>
    .auto-stats span{
        font-size: 23px;
    }
    </style>
    <div class="content">
        <!-- Start content -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title-box pull-right">
                        <ol class="breadcrumb p-0 m-0">
                            <li> <a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="active"> Shared Emails </li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header card-header-text" data-background-color="rose">
                            <h3 class="card-title"> Import Emails </h3>
                        </div>

                        <div class="card-content">
                            <form role="form" id="import_shared_emails" >
                                {{ csrf_field() }}
                                <input type="hidden" class="account_id" name="account">
                                <input type="hidden" class="target" name="target">
                                <div class="form-group">
                                    <div class="col-md-2">
                                        <label for="category">Import code:</label>
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" name="shared_code" id="shared_code" class="form-control" placeholder="Enter code here" value="" required autocomplete="off">

                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-2"></div>
                                        <div class="col-md-8">
                                            <button type="submit" class="btn btn-sm btn-success pull-right m-t-10">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <!-- imported emails templates  -->
                <div class="col-xs-12">
                    <div class="card-box">
                        <div class="material-datatables">
                            <table id="load_datatable_imported" class="table table-bordered table-no-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>From</th>
                                    <th>Total</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td colspan="5">No Record found yet.</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form action="{{ route('new-template.create') }}" method="get" style="display: none;" id="use_me">
            <input type="hidden" name="use_me" value="">
        </form>

        <script>
            function submitUseMe(x){
                $('input[name="use_me"]').val($(x).data('id'));
                $('#use_me').submit();
            }
        </script>

        <script>

            $(document).ready(function(){

                $('#load_datatable_imported').DataTable({

                    "pageLength":25,
                    "order": [[0, 'desc']],
                    processing: true,
                    serverSide: true,
                    "initComplete": function (settings, json) {
                    },
                    "drawCallback": function () {
                        //table_draw();
                        /*$("[name='status']").bootstrapSwitch();
                         changeStatus();*/
                    },
                    ajax: "{!! Route('load-shared-emails') !!}",
                    columns: [
                        {data: 'index', name: 'index'},
                        {data: 'title', name: 'title'},
                        {data: 'user_name', name: 'user_name'},
                        {data: 'total', name: 'total'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                        //{data: 'sent', name: 'sent', orderable: false, searchable: false},

                    ]
                });

                // import emails code
                $("#import_shared_emails").submit(function(){
                    $('#loading').show();
                    var data = new FormData(this);
                    $.ajax({url: "{{ route('fetch-shared-emails') }}",data: data,
                        contentType: false,
                        processData: false,
                        responsive: true,
                        type: 'POST',
                        success: function(result){
                            $('#loading').hide();
                            if(result == '1'){
                                $('#import_shared_emails_pop').modal('hide');
                                $('#shared_code').val('');
                                swal({  title: "Good job!", text: "Shared Emails are fetched successfully!", type: "success" });
                            }else if(result == 3){
                                swal("Warning!", "The code is already used!", "warning");
                            }else if(result == 4){
                                swal("Warning!", "Invalid code", "warning");
                            }else if (result == 5){
                                swal("Warning!", "Shared code haven't email to import", "warning");
                            }
                            else{
                                swal("Error!", "Something went wrong.", "error");
                            }
                        }
                    });
                    return false;
                });

            });

        </script>


    </div>
    <!-- Counter js  -->
    <script src="{{ asset('plugins/waypoints/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('plugins/counterup/jquery.counterup.min.js') }}"></script>
@endsection

resources/views/admin/ar_campaign/shared_emails_detail.blade.php
@extends('layouts.app')

@section('content')

    <style>

    .auto-stats span{
        font-size: 23px;
    }

    </style>
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title-box">

                        <ol class="breadcrumb p-0 m-0">
                            <li> <a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
                            <li> <a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
                            <li class="active"> My Emails </li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="row">

                <!-- imported emails templates  -->
                <div class="col-xs-12">
                    <div class="card-box">
                        <table id="load_datatable_imported" class="table table-bordered table-no-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Subject</th>
                                <th>Category</th>
                                <th width="70">Type</th>
                                <!--<th>Send</th>-->

                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="5">No Record found yet.</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <form action="{{ route('new-template.create') }}" method="get" style="display: none;" id="use_me">
            <input type="hidden" name="use_me" value="">
        </form>

        <script>
            function submitUseMe(x){
                $('input[name="use_me"]').val($(x).data('id'));
                $('#use_me').submit();
            }
        </script>

        <script>

            $(document).ready(function(){

                $('#load_datatable_imported').DataTable({

                    "pageLength":25,
                    "order": [[0, 'desc']],
                    processing: true,
                    serverSide: true,
                    "initComplete": function (settings, json) {
                    },
                    ajax: "{!! Route('shared-emails-detail') !!}?sub_id={{ $sub_id }}",
                    columns: [
                        {data: 'id', name: 'id'},
                        {data: 'subject', name: 'email_subjects_test.subject'},
                        {data: 'category', name: 'email_sub_category.category'},
                        {data: 'type', name: 'email_sub_category.type'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                        //{data: 'sent', name: 'sent', orderable: false, searchable: false},

                    ]
                });
            });

        </script>


    </div>
    <!-- Counter js  -->
    <script src="{{ asset('plugins/waypoints/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('plugins/counterup/jquery.counterup.min.js') }}"></script>
@endsection