routes/web.php
<?php

/*
clear cache
*/

Route::get('/clear-cache', function() {
    Artisan::call('view:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    echo 'view, cache, route cache cleared successfully!';
});


Route::get('/', function () {
    if(!Auth::User()){
        if(file_exists(storage_path('installed')))
        {
            return view('auth.login');
            die();
        }else{
            header("location: public/install");
            die();
        }

    }else{
        return redirect('home');
    }
});

Route::any('callback', 'CallBackController@callBack');
Route::any('add-user', 'Admin\UserController@store');

Route::post('send-password', 'Admin\UserController@userSendPassword')->name('send-password');

Route::get('find-synonyms/{word?}', 'Admin\WordApiController@index');
Route::get('mailchimp', 'Admin\MailChimpController@index');
Route::get('cron',      'CronController@index');
Route::get('fetch-emails-cron',      'CronController@fetchEmailsCron')->name('fetch-emails-cron');
Route::get('cronejob-autoresponder-contacts', 'CronController@fetchAutorespondersContacts')->name('cronejob-autoresponder-contacts');

Route::get('schedule-autoresponders', 'CronController@scheduleAutoresponders');
Route::get('schedule-aweber-broadcast', 'CronController@scheduleAweberBroadcast');
Route::get('test-cron', 'CronController@testCron');
Route::get('aweber-fetch-contacts', 'CronController@aweberFetchContacts');
Route::get('getresponse-fetch-contacts', 'CronController@getresponseFetchContacts');
Route::get('mailchimp-fetch-contacts', 'CronController@mailchimpFetchContacts');
Route::get('activecampaign-fetch-contacts', 'CronController@activecampaignFetchContacts');
// auth autoresponders
Route::get('autoresponders-lists', 'CronController@autoresponderFetchLists');

// test

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('home', 'HomeController@index')->name('home');

    Route::get('help', 'Admin\HelpController@index')->name('help');
    Route::get('link_tracker', 'HomeController@linkTracker');
    Route::get('link_tracker_settings', 'HomeController@linkTrackerSettings');
    Route::post('link_tracker_settings_store', 'HomeController@linkTrackerSettingsStore');
});
// home chart
Route::post('load-broadcast-chart',  'HomeController@broadcastChart')->name('load-broadcast-chart');

// common routes for admin and user
Route::group(['namespace'=>'Admin','middleware' => ['auth']], function(){

    Route::resource('category',  'CategoryController');
    Route::resource('new-template',  'NewEmailTemplateController');
    Route::resource('new-template2',  'NewEmailTemplateController2');
    Route::resource('settings',  'SettingController');
    Route::resource('gen_settings',  'SettingNewController');
    Route::resource('gallery',  'GalleryController');

    Route::resource('email-header-footer-settings',  'EmailHeaderFooterController');
    Route::resource('contact_info',  'ContactInfoController');
    Route::resource('report',  'ReportController');
    Route::resource('ar-campaigns',  'ArCampaignController');
    Route::resource('email-sub-category',  'SubEmailCategoryController');
    Route::resource('contacts',  'ContactsController');
    Route::resource('app-settings',  'AppSettingsController');

    Route::resource('contact-list',  'ContactListController');
    Route::get('load_list', 'ContactListController@loadList')->name('load_list');

    /* update */
    Route::get('/update-version', function (){
        return view('admin.update.index');
    });
    Route::post('updates', 'AppSettingsController@serverUpdate');


    Route::get('profile',  'UserController@loadProfileSetting')->name('profile');
    Route::post('profile-settings',  'UserController@profileSetting')->name('profile-settings');

    Route::post('browse-gallery',  'GalleryController@browseGallery')->name('browse-gallery');

    Route::get('choose-subject',       'NewEmailTemplateController@searchSubject')->name('choose-subject');
    Route::post('email_content_by_id',  'NewEmailTemplateController@loadEmailContentByID')->name('email_content_by_id');
    Route::post('download-email',       'NewEmailTemplateController@downloadEmail')->name('download-email');
    Route::post('load-searched-email',  'NewEmailTemplateController@loadSearchedEmail')->name('load-searched-email');
    Route::post('view-email-content',  'NewEmailTemplateController@viewEmailContent')->name('view-email-content'); /// added  5-5

    Route::post('fetch-emails',  'SettingNewController@fetchEmails')->name('fetch-emails'); //setting controller
    Route::post('sharing-code-gen',  'SettingNewController@sharingCodeGenerator')->name('sharing-code-gen'); //setting controller

    Route::get('cpanel-account',  'SettingNewController@cpanelAccount')->name('cpanel-account'); //setting controller # server creation

    // my emails
    Route::get('shared-emails',  'ArCampaignController@sharedEmails')->name('shared-emails');
    Route::post('fetch-shared-emails',  'ArCampaignController@fetchSharedEmails')->name('fetch-shared-emails');

    // your email contents
    Route::get('load-your-email-contents',  'AjaxController@loadYourEmailContent')->name('load-your-email-content');

    Route::get('load-my-emails',  'AjaxController@loadMyEmails')->name('load-my-emails');
    Route::get('load-shared-emails',  'AjaxController@loadSharedEmails')->name('load-shared-emails');
    Route::get('shared-emails-detail',  'AjaxController@sharedEmailsDetail')->name('shared-emails-detail');
    Route::get('load-contacts',  'AjaxController@loadContacts')->name('load-contacts');
    Route::get('load-lists',  'AjaxController@loadLists')->name('load-lists');
    Route::get('load-open-by_emails',  'AjaxController@loadOpenByEmail')->name('load-open-by_emails');
    Route::get('load-unopen-by_emails',  'AjaxController@loadUnopenByEmail')->name('load-unopen-by_emails');

    Route::get('opened-report',  'ContactsController@showOpenReport');
    Route::get('unopened-report',  'ContactsController@showUnOpenReport');

    // load_ar_campains list of get-response/aweber
    Route::get('load_ar_api_key',  'NewEmailTemplateController@selectArApi')->name('load_ar_api_key');
    Route::get('load_ar_campaings',  'NewEmailTemplateController@loadArCampaings')->name('load_ar_campaings');


    Route::post('get-aweber-token',  'AweberController@getAccessToken')->name('get-aweber-token');
    Route::any('aweber-callback',  'AweberController@aweberCallback')->name('aweber-callback');

    Route::post('get-aweber-auth',  'AweberNewController@getAccessToken')->name('get-aweber-auth');
    Route::any('aweber-callback-auth',  'AweberNewController@aweberCallback')->name('aweber-callback-auth');

    Route::post('delete',  'AjaxController@delete')->name('delete');
    Route::post('delete-email',  'AjaxController@deleteEmail')->name('delete-email');

    // test
    Route::get('report',  'ReportController@index')->name('report');

    Route::get('autoresponder-report',  'ReportController@reportById')->name('autoresponder-report');
    Route::get('type-wise-stats',  'ReportController@typewiseReport')->name('type-wise-stats');

    Route::get('testreport',  'ReportController@test')->name('testreport');

    Route::post('private-email', 'AjaxController@privateEmail')->name('private-email');
    Route::get('load-sub-categories',  'AjaxController@loadSubCategories')->name('load-sub-categories');
    Route::get('load-sub-categories-emails',  'AjaxController@loadSubCategoriesEmails')->name('load-sub-categories-emails');
    Route::get('show_boradcast_error',  'AjaxController@showBoradcastError')->name('show_boradcast_error');
    Route::post('sync_stats',  'AjaxController@syncStats')->name('sync_stats');

    Route::post('email-sub-category/loadEdit',  'SubEmailCategoryController@loadEdit');
    Route::get('assign-category',  'SubEmailCategoryController@assignCategory')->name('assign-category');
    Route::post('save-assign-category',  'SubEmailCategoryController@saveAssignCategory')->name('save-assign-category');

    Route::post('email_sender_settings',  'SettingController@emailSenderSettings')->name('email_sender_settings');

});

Route::group(['namespace'=>'Admin','middleware' => ['auth','checkAdmin']], function(){

    Route::resource('library', 'SubjectTemplateController');
    Route::resource('email-template',  'EmailTemplateController');
//    Route::resource('category',  'CategoryController');
    Route::resource('users',  'UserController');
    Route::resource('email-settings',  'UserEmailSettings');


    Route::post('user/loadEdit',  'UserController@loadEdit');
    Route::post('category/loadEdit',  'CategoryController@loadEdit');

    Route::get('load-categories',  'AjaxController@loadCategories')->name('load-categories');

    Route::get('load-users',  'AjaxController@loadUsers')->name('load-users');

    Route::get('load-subjects',  'AjaxController@loadSubjects')->name('load-subjects');
    Route::get('load-email-content',  'AjaxController@loadEmailContent')->name('load-email-content');

    Route::post('changeStatus',  'AjaxController@changeStatus')->name('changeStatus');
    Route::get('load-emailtracking-stats',  'AjaxController@loadTrackingStats')->name('load-emailtracking-stats');

    Route::post('user-stats',  'UserController@userStats')->name('user-stats');

    Route::post('email-settings-store', 'UserEmailSettings@saveEmailSettings')->name('email-settings-store');
    Route::post('test-email', 'UserEmailSettings@testEmail')->name('test-email');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','plain_password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/admin/user/email_notification.blade.php
{!! $content !!}

<br><br>
Regards,<br><strong>{{ config('app.name') }}</strong>

resources/views/admin/user/email_test.blade.php
{This is test email

<br><br>
Regards,<br><strong>{{ config('app.name') }}</strong>

resources/views/admin/user/list.blade.php
@extends('layouts.app')
@section('title', 'Users')
@section('content')
<style>
    form#add_user .loader {
        float: right;
        margin-left: 5px;
        margin-top: 6px;
    }
    form#add_user .loader img{
        display: none;
    }
    .add_more{
        float: right;
        margin-bottom: 5px;
    }

</style>
    <div class="content">
        <!-- Start content -->
        <div class="container-fluid">
            <div class="col-xs-12">
                <div class="page-title-box pull-right">
                    <ol class="breadcrumb p-0 m-0">
                        <li> <a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
                        <li class="active"> Users </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>

            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header card-header-text" data-background-color="rose">
                    <h3 class="card-title"> Manage Users </h3>
                </div>
                <div class="add_more m-r-10">
                    <button type="button" class="btn btn-success w-md " onclick='addUser()' >Create User</button>
                </div>
                <div class="card-content">
                    <div class="material-datatables">
                        <table id="load_datatable" class="table table-colored table-inverse table-hover table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Dated</th>
                                <th>Status&nbsp;|&nbsp;Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="4">No Record found yet.</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
<!--  add user -->
<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title text-center">Add New User</h4>
            </div>

            <form id="add_user" method="post" role="form" >
                <input type="hidden" name="id" value="" id="id" >
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Name:</label>
                                <input type="text" name="name" class="form-control" value="" id="name" placeholder="name" required >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Email:</label>
                                <input type="email" name="email" class="form-control" value="" id="email" placeholder="valid email" required >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Password:</label>
                                <input type="text" name="password" class="form-control" value="" id="plain_password" placeholder="password" required >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Email category:</label>
                                <select name="email_category[]" class="form-control" id="email_category" multiple required >
                                    <option value="0">None</option>
                                    @foreach($email_category as $value)
                                    <option value="{{ $value->id }}">{{ $value->category }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12" id="c_info"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-xs" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success btn-xs">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- usre stats modal  -->
<div id="user_stat" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>

<!-- /.modal -->
<script>
    $(document).ready(function(){

        //saving new user
        $("#add_user").submit(function(){
            $('#loading').show();
            var data = new FormData(this);
            $.ajax({
                url: "<?php echo route('users.store'); ?>",
                data: data,
                contentType: false,
                processData: false,
                type: 'POST',
                success: function(result){
                    $('#loading').hide();

                    var json_obj = JSON.parse(result);

                    if(json_obj.msg!='0'){
                        $('#add_user')[0].reset();
                        $("#id").val("");
                        $("#con-close-modal").modal('hide');
                        //$("#c_info").html(result);
                        //$("#c_info").append(result);
                        refreshTable();
                        if(json_obj.msg=='1'){
                            swal("Success!", "User has been saved successfully", "success");
                        }
                    }else{
                        swal("Error!", "Something went wrong.", "error");
                    }
                }
            });
            return false;
        });

        $("[name='status']").bootstrapSwitch();

        $('#load_datatable').DataTable({
            "pageLength":25,
            "order": [[0, 'desc']],
            processing: true,
            serverSide: true,
            responsive:true,
            "initComplete": function (settings, json) {

            },
            "drawCallback": function () {
                //table_draw();
                $("[name='status']").bootstrapSwitch();
                changeStatus();
            },
            ajax: "{!! Route('load-users') !!}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });

    function addUser(){
        $("#con-close-modal").modal('show');
    }
    function editRow(x){
        $('#loading').show();
        if(x!=''){
            $.post("<?php echo url('user/loadEdit'); ?>", {id: x}, function(result){
                if(result!='0'){
                    var data = JSON.parse(result);
                    var cat_array = data.email_category.split(',');
                    $.each(data, function(k,v){
                        var ref = $("#add_user").find("#"+k);
                        $(ref).val(v);
                        $("#con-close-modal").modal('show');
                    });

                    $('#email_category > option').attr('selected',false);

                    $('#email_category > option').each(function() {

                        $(this).attr('selected', false).removeClass('bg-gray');
                        $(this).prop('selected', false).removeClass('bg-gray');

                        for( var i = 0; i < cat_array.length; i++){
                            if( cat_array[i] == $(this).val() ){
                                $(this).prop('selected', 'selected').addClass('bg-gray');
                            }
                        }
                    });

                    var cat_array = data.email_category.split(',');
                    //console.log(cat_array_length);
                }else{
                    swal("Error!", "Something went wrong.", "error");
                }
                $('#loading').hide();
            }
            );
        }
    }

    function showStats(e){
        $('#loading').show();
         var user_id =   $(e).data('id');
         if( user_id != '' ){
            $.post("<?php echo route('user-stats'); ?>", {user_id: user_id}, function(result){
                if(result!='0'){

                    $('#user_stat').html(result);

                    $('#user_stat').modal('show');
                    $('#loading').hide();
                }else{
                    swal("Error!", "Something went wrong.", "error");
                }
                $('#loading').hide();
            }
            );
        }
    }

</script>
@endsection

resources/views/admin/user/stats.blade.php
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                <i class="material-icons">clear</i>
            </button>
            <h4 class="modal-title text-center">User Stats</h4>
        </div>
        <div class="modal-body">
            <table id="load_datatable" class="table table-colored table-inverse table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th>Templates</th>
                    <th>Opened</th>
                    <th>Clicked</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?= $templates ?></td>
                    <td><?= $opened ?></td>
                    <td><?= $clicked ?></td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>